application: webcamlocation
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /cronny
  script: main.app
  login: admin
- url: /all/
  script: main.app
  login: admin
- url: /static
  static_dir: static
- url: .*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: numpy
  version: "1.6.1"
- name: PIL
  version: latest
  
env_variables:
  GAE_USE_SOCKETS_HTTPLIB : 'anyvalue'
